---
- name: Render atom user preferences
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.atom/config.cson"
    create: true
    block: |
      {{ macos_atom.preferences | to_nice_json }}
  when: macos_atom.preferences
