---
- name: Install atom packages
  shell: "apm list --bare | grep -E '^{{ item }}@' && echo 'Already installed.' || apm install '{{ item }}'"
  with_items: "{{ macos_atom.packages }}"
  register: apm_result
  changed_when: "'Already installed.' not in apm_result.stdout"
